### ISSUE TITLE
Add Travis build for Node v0.12

### ISSUE THREAD

**Issue by mauvm** [kukua/concava#10]
Removed in cb328d7, since it throws an error I can't reproduce.<br/>Tested in Docker containers `node:0.12.7` and `node:0.12.7-wheezy`.

```
Using worker: worker-linux-docker-fbaa2e02.prod.travis-ci.org:travis-linux-3
system_info
Build system information
Build language: node_js
Build image provisioning date and time
Thu Feb  5 15:09:33 UTC 2015
Operating System Details
Distributor ID:	Ubuntu
Description:	Ubuntu 12.04.5 LTS
Release:	12.04
Codename:	precise
Linux Version
3.13.0-29-generic
Cookbooks Version
a68419e https://github.com/travis-ci/travis-cookbooks/tree/a68419e
GCC version
gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3
Copyright (C) 2011 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
LLVM version
clang version 3.4 (tags/RELEASE_34/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
Pre-installed Ruby versions
ruby-1.9.3-p551
Pre-installed Node.js versions
v0.10.36
Pre-installed Go versions
1.4.1
Redis version
redis-server 2.8.19
riak version
2.0.2
MongoDB version
MongoDB 2.4.12
CouchDB version
couchdb 1.6.1
Neo4j version
1.9.4
RabbitMQ Version
3.4.3
ElasticSearch version
1.4.0
Installed Sphinx versions
2.0.10
2.1.9
2.2.6
Default Sphinx version
2.2.6
Installed Firefox version
firefox 31.0esr
PhantomJS version
1.9.8
ant -version
Apache Ant(TM) version 1.8.2 compiled on December 3 2011
mvn -version
Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T17:29:23+00:00)
Maven home: /usr/local/maven
Java version: 1.7.0_76, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-7-oracle/jre
Default locale: en_US, platform encoding: ANSI_X3.4-1968
OS name: "linux", version: "3.13.0-29-generic", arch: "amd64", family: "unix"
git.checkout
0.36s$ git clone --depth=50 --branch=master https://github.com/kukua/concava.git kukua/concava
Cloning into 'kukua/concava'...
remote: Counting objects: 307, done.
remote: Compressing objects: 100% (122/122), done.
remote: Total 307 (delta 193), reused 293 (delta 181), pack-reused 0
Receiving objects: 100% (307/307), 48.18 KiB | 0 bytes/s, done.
Resolving deltas: 100% (193/193), done.
Checking connectivity... done.
$ cd kukua/concava
$ git checkout -qf f95cc0d692a118a360d3cad70cbc7563d541e770
This job is running on container-based infrastructure, which does not allow use of 'sudo', setuid and setguid executables.
If you require sudo, add 'sudo: required' to your .travis.yml
See http://docs.travis-ci.com/user/workers/container-based-infrastructure/ for details.
2.37s$ nvm install 0.12
######################################################################## 100.0%
Now using node v0.12.7
$ node --version
v0.12.7
$ npm --version
2.11.3
$ nvm --version
0.23.3
install
93.42s$ npm install 
> spawn-sync@1.0.14 postinstall /home/travis/build/kukua/concava/node_modules/pre-commit/node_modules/cross-spawn/node_modules/spawn-sync
> node postinstall
> pre-commit@1.1.2 install /home/travis/build/kukua/concava/node_modules/pre-commit
> node install.js
npm WARN optional dep failed, continuing fsevents@1.0.5
vm2@0.2.3 node_modules/vm2
connect@3.4.0 node_modules/connect
├── utils-merge@1.0.0
├── parseurl@1.3.0
├── debug@2.2.0 (ms@0.7.1)
└── finalhandler@0.4.0 (unpipe@1.0.0, escape-html@1.0.2, on-finished@2.3.0)
raw-body@2.1.4 node_modules/raw-body
├── bytes@2.1.0
├── unpipe@1.0.0
└── iconv-lite@0.4.12
jasmine@2.3.2 node_modules/jasmine
├── exit@0.1.2
├── jasmine-core@2.3.4
└── glob@3.2.11 (inherits@2.0.1, minimatch@0.3.0)
pre-commit@1.1.2 node_modules/pre-commit
├── which@1.1.2 (is-absolute@0.1.7)
└── cross-spawn@2.0.0 (cross-spawn-async@2.0.0, spawn-sync@1.0.14)
request@2.65.0 node_modules/request
├── aws-sign2@0.6.0
├── forever-agent@0.6.1
├── caseless@0.11.0
├── stringstream@0.0.5
├── tunnel-agent@0.4.1
├── oauth-sign@0.8.0
├── isstream@0.1.2
├── json-stringify-safe@5.0.1
├── extend@3.0.0
├── node-uuid@1.4.7
├── combined-stream@1.0.5 (delayed-stream@1.0.0)
├── qs@5.2.0
├── tough-cookie@2.2.1
├── mime-types@2.1.7 (mime-db@1.19.0)
├── form-data@1.0.0-rc3 (async@1.5.0)
├── http-signature@0.11.0 (assert-plus@0.1.5, asn1@0.1.11, ctype@0.5.3)
├── bl@1.0.0 (readable-stream@2.0.4)
├── har-validator@2.0.2 (pinkie-promise@1.0.0, commander@2.9.0, chalk@1.1.1, is-my-json-valid@2.12.3)
└── hawk@3.1.1 (cryptiles@2.0.5, sntp@1.0.9, boom@2.10.1, hoek@2.16.3)
babel-cli@6.1.18 node_modules/babel-cli
├── slash@1.0.0
├── log-symbols@1.0.2
├── path-is-absolute@1.0.0
├── path-exists@1.0.0
├── fs-readdir-recursive@0.1.2
├── convert-source-map@1.1.2
├── v8flags@2.0.10 (user-home@1.1.1)
├── commander@2.9.0 (graceful-readlink@1.0.1)
├── chalk@1.1.1 (escape-string-regexp@1.0.3, supports-color@2.0.0, ansi-styles@2.1.0, strip-ansi@3.0.0, has-ansi@2.0.0)
├── output-file-sync@1.1.1 (xtend@4.0.1, mkdirp@0.5.1)
├── glob@5.0.15 (inherits@2.0.1, once@1.3.2, inflight@1.0.4, minimatch@3.0.0)
├── source-map@0.5.3
├── bin-version-check@2.1.0 (minimist@1.2.0, semver@4.3.6, semver-truncate@1.1.0, bin-version@1.0.4)
├── chokidar@1.2.0 (arrify@1.0.0, glob-parent@2.0.0, async-each@0.1.6, is-binary-path@1.0.1, is-glob@2.0.1, lodash.flatten@3.0.2, readdirp@2.0.0, anymatch@1.3.0)
├── babel-core@6.1.21 (babel-messages@6.1.18, babel-template@6.1.18, shebang-regex@1.0.0, private@0.1.6, babel-helpers@6.1.20, esutils@2.0.2, home-or-tmp@1.0.0, debug@2.2.0, babel-types@6.1.18, minimatch@2.0.10, babel-code-frame@6.1.18, babylon@6.1.21, babel-generator@6.1.20, babel-traverse@6.1.20, json5@0.4.0, source-map-support@0.2.10, regenerator@0.8.35)
├── lodash@3.10.1
├── babel-register@6.1.18 (home-or-tmp@1.0.0, source-map-support@0.2.10, core-js@1.2.6)
├── babel-polyfill@6.1.19 (regenerator@0.8.42, core-js@1.2.6)
└── babel-runtime@5.8.34 (core-js@1.2.6)
babel-preset-es2015@6.1.18 node_modules/babel-preset-es2015
├── babel-plugin-transform-es2015-arrow-functions@6.1.18 (babel-runtime@5.8.34)
├── babel-plugin-transform-es2015-computed-properties@6.1.18 (babel-helper-define-map@6.1.18, babel-template@6.1.18, babel-runtime@5.8.34)
├── babel-plugin-check-es2015-constants@6.1.18 (babel-runtime@5.8.34)
├── babel-plugin-transform-es2015-spread@6.1.18 (babel-runtime@5.8.34)
├── babel-plugin-transform-es2015-block-scoped-functions@6.1.18 (babel-runtime@5.8.34)
├── babel-plugin-transform-es2015-object-super@6.1.18 (babel-helper-replace-supers@6.1.18, babel-runtime@5.8.34)
├── babel-plugin-transform-es2015-template-literals@6.1.18 (babel-runtime@5.8.34)
├── babel-plugin-transform-es2015-typeof-symbol@6.1.18 (babel-runtime@5.8.34)
├── babel-plugin-transform-es2015-unicode-regex@6.1.18 (regexpu@1.3.0, babel-helper-regex@6.1.18, babel-runtime@5.8.34)
├── babel-plugin-transform-es2015-sticky-regex@6.1.18 (babel-helper-regex@6.1.18, babel-types@6.1.18, babel-runtime@5.8.34)
├── babel-plugin-transform-es2015-for-of@6.1.18 (babel-runtime@5.8.34)
├── babel-plugin-transform-es2015-function-name@6.1.18 (babel-types@6.1.18, babel-helper-function-name@6.1.18, babel-runtime@5.8.34)
├── babel-plugin-transform-es2015-literals@6.1.18 (babel-runtime@5.8.34)
├── babel-plugin-transform-es2015-destructuring@6.1.18 (babel-runtime@5.8.34)
├── babel-plugin-transform-es2015-shorthand-properties@6.1.18 (babel-types@6.1.18, babel-runtime@5.8.34)
├── babel-plugin-transform-es2015-modules-commonjs@6.1.20 (babel-plugin-transform-strict-mode@6.1.18, babel-template@6.1.18, babel-types@6.1.18, babel-runtime@5.8.34)
├── babel-plugin-transform-es2015-parameters@6.1.18 (babel-helper-get-function-arity@6.1.18, babel-helper-call-delegate@6.1.18, babel-template@6.1.18, babel-types@6.1.18, babel-traverse@6.1.20, babel-runtime@5.8.34)
├── babel-plugin-transform-es2015-classes@6.1.21 (babel-helper-optimise-call-expression@6.1.18, babel-messages@6.1.18, babel-helper-replace-supers@6.1.18, babel-helper-function-name@6.1.18, babel-helper-define-map@6.1.18, babel-template@6.1.18, babel-types@6.1.18, babel-traverse@6.1.20, babel-runtime@5.8.34)
├── babel-plugin-transform-es2015-block-scoping@6.1.18 (babel-types@6.1.18, babel-template@6.1.18, babel-traverse@6.1.20, lodash@3.10.1, babel-runtime@5.8.34)
└── babel-plugin-transform-regenerator@6.1.18 (babel-plugin-syntax-async-functions@6.1.18, private@0.1.6, through@2.3.8, babylon@6.1.21, commoner@0.10.4, babel-types@6.1.18, babel-traverse@6.1.20, babel-core@6.1.21, babel-runtime@5.8.34)
eslint@1.9.0 node_modules/eslint
├── escape-string-regexp@1.0.3
├── path-is-absolute@1.0.0
├── object-assign@4.0.1
├── to-double-quotes@2.0.0
├── to-single-quotes@2.0.0
├── path-is-inside@1.0.1
├── xml-escape@1.0.0
├── strip-json-comments@1.0.4
├── estraverse-fb@1.3.1
├── globals@8.12.0
├── estraverse@4.1.1
├── text-table@0.2.0
├── esutils@2.0.2
├── user-home@2.0.0 (os-homedir@1.0.1)
├── is-resolvable@1.0.0 (tryit@1.0.2)
├── debug@2.2.0 (ms@0.7.1)
├── chalk@1.1.1 (supports-color@2.0.0, ansi-styles@2.1.0, strip-ansi@3.0.0, has-ansi@2.0.0)
├── json-stable-stringify@1.0.0 (jsonify@0.0.0)
├── lodash.merge@3.3.2 (lodash.isarguments@3.0.4, lodash.isarray@3.0.4, lodash._arraycopy@3.0.0, lodash._arrayeach@3.0.0, lodash.keysin@3.0.8, lodash.istypedarray@3.0.2, lodash._getnative@3.9.1, lodash.keys@3.1.2, lodash._createassigner@3.1.1, lodash.isplainobject@3.2.0, lodash.toplainobject@3.0.0)
├── glob@5.0.15 (inherits@2.0.1, once@1.3.2, inflight@1.0.4)
├── minimatch@3.0.0 (brace-expansion@1.1.1)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── shelljs@0.5.3
├── optionator@0.6.0 (fast-levenshtein@1.0.7, type-check@0.3.1, deep-is@0.1.3, levn@0.2.5, wordwrap@0.0.3, prelude-ls@1.1.2)
├── doctrine@0.7.1 (isarray@0.0.1, esutils@1.1.6)
├── lodash.omit@3.1.0 (lodash._arraymap@3.0.0, lodash._bindcallback@3.0.1, lodash._pickbyarray@3.0.2, lodash.restparam@3.6.1, lodash._baseflatten@3.1.4, lodash.keysin@3.0.8, lodash._pickbycallback@3.0.0, lodash._basedifference@3.0.3)
���── lodash.clonedeep@3.0.2 (lodash._bindcallback@3.0.1, lodash._baseclone@3.3.0)
├── concat-stream@1.5.1 (inherits@2.0.1, typedarray@0.0.6, readable-stream@2.0.4)
├── espree@2.2.5
├── is-my-json-valid@2.12.3 (jsonpointer@2.0.0, generate-function@2.0.0, xtend@4.0.1, generate-object-property@1.2.0)
├── file-entry-cache@1.2.4 (flat-cache@1.0.10)
├── inquirer@0.11.0 (strip-ansi@3.0.0, ansi-regex@2.0.0, figures@1.4.0, ansi-escapes@1.1.0, cli-width@1.1.0, through@2.3.8, run-async@0.1.0, readline2@1.0.1, cli-cursor@1.0.2, rx-lite@3.1.2, lodash@3.10.1)
├── js-yaml@3.4.3 (esprima@2.7.0, argparse@1.0.3)
├── handlebars@4.0.4 (async@1.5.0, source-map@0.4.4, optimist@0.6.1, uglify-js@2.4.24)
└── escope@3.2.0 (esrecurse@3.1.1, estraverse@3.1.0, es6-map@0.1.2, es6-weak-map@0.1.4)
7.13s$ npm test
> concava@0.1.0 test /home/travis/build/kukua/concava
> babel-node spec/run.js
/home/travis/build/kukua/concava/src/Calibrator.js:19
var Calibrator = class Calibrator {
                 ^^^^^
SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at loader (/home/travis/build/kukua/concava/node_modules/babel-cli/node_modules/babel-register/lib/node.js:128:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/travis/build/kukua/concava/node_modules/babel-cli/node_modules/babel-register/lib/node.js:138:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/travis/build/kukua/concava/spec/CalibratorSpec.js:3:19)
    at Module._compile (module.js:460:26)
npm ERR! Test failed.  See above for more details.
The command "npm test" exited with 1.
Done. Your build exited with 1.
```

**Comment by mauvm** [comment]
Will add if requested.
