### ISSUE TITLE
Add error message for payload length mismatch

### ISSUE THREAD

**Issue by mauvm** [kukua/concava#25]
If the converters require more/less bytes than given, respond with proper error.

**Comment by mauvm** [comment]
```
[RangeError: index out of range]
RangeError: index out of range
    at checkOffset (buffer.js:619:11)
    at Buffer.readUInt16LE (buffer.js:665:5)
    at Object.<anonymous> (convert.js:5:47)
    at Converter.js:36:18
    at Array.forEach (native)
    at Converter.js:31:25
    at Array.forEach (native)
    at Converter.convert (Converter.js:30:14)
    at concava.js:13:13
    at call (/data/node_modules/connect/index.js:239:7)
```
